// Load .env.local for local development (prisma studio / tsx seed.ts)
import { config } from "dotenv";
config({ path: ".env.local", override: false });

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Type helpers for seed data — avoids dependency on generated enums
// before `prisma generate` has run
type FoodCategoryStr = string;
type ServingUnitStr = string;

interface FoodSeed {
  name: string;
  category: FoodCategoryStr;
  caloriesPer100g: number;
  proteinPer100g: number;
  carbsPer100g: number;
  fatPer100g: number;
  fiberPer100g?: number;
  defaultServingSizeG: number;
  defaultServingUnit: ServingUnitStr;
  isVerified: boolean;
}

const foods = [
  // ─── GRAINS & CEREALS ───────────────────────────────────────
  {
    name: "White Rice (Cooked)",
    category: "GRAINS_CEREALS",
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbsPer100g: 28.2,
    fatPer100g: 0.3,
    fiberPer100g: 0.4,
    defaultServingSizeG: 200,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Brown Rice (Cooked)",
    category: "GRAINS_CEREALS",
    caloriesPer100g: 123,
    proteinPer100g: 2.7,
    carbsPer100g: 25.6,
    fatPer100g: 0.9,
    fiberPer100g: 1.8,
    defaultServingSizeG: 200,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Basmati Rice (Cooked)",
    category: "GRAINS_CEREALS",
    caloriesPer100g: 121,
    proteinPer100g: 3.5,
    carbsPer100g: 25.2,
    fatPer100g: 0.4,
    fiberPer100g: 0.4,
    defaultServingSizeG: 200,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Rolled Oats (Dry)",
    category: "GRAINS_CEREALS",
    caloriesPer100g: 379,
    proteinPer100g: 13.2,
    carbsPer100g: 67.7,
    fatPer100g: 6.9,
    fiberPer100g: 10.1,
    defaultServingSizeG: 60,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Wheat Roti / Chapati (1 piece ~40g)",
    category: "GRAINS_CEREALS",
    caloriesPer100g: 297,
    proteinPer100g: 8.5,
    carbsPer100g: 56.4,
    fatPer100g: 5.8,
    fiberPer100g: 2.2,
    defaultServingSizeG: 40,
    defaultServingUnit: "piece",
    isVerified: true,
  },
  {
    name: "Whole Wheat Bread",
    category: "GRAINS_CEREALS",
    caloriesPer100g: 247,
    proteinPer100g: 9.0,
    carbsPer100g: 44.0,
    fatPer100g: 3.5,
    fiberPer100g: 6.0,
    defaultServingSizeG: 30,
    defaultServingUnit: "slice",
    isVerified: true,
  },
  {
    name: "Idli (1 piece ~45g)",
    category: "GRAINS_CEREALS",
    caloriesPer100g: 58,
    proteinPer100g: 2.0,
    carbsPer100g: 11.4,
    fatPer100g: 0.5,
    fiberPer100g: 0.5,
    defaultServingSizeG: 45,
    defaultServingUnit: "piece",
    isVerified: true,
  },
  {
    name: "Dosa (plain, ~75g)",
    category: "GRAINS_CEREALS",
    caloriesPer100g: 171,
    proteinPer100g: 3.9,
    carbsPer100g: 31.5,
    fatPer100g: 3.7,
    fiberPer100g: 0.5,
    defaultServingSizeG: 75,
    defaultServingUnit: "piece",
    isVerified: true,
  },
  {
    name: "Poha (Cooked)",
    category: "GRAINS_CEREALS",
    caloriesPer100g: 180,
    proteinPer100g: 3.5,
    carbsPer100g: 36.0,
    fatPer100g: 3.0,
    fiberPer100g: 0.8,
    defaultServingSizeG: 150,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Quinoa (Cooked)",
    category: "GRAINS_CEREALS",
    caloriesPer100g: 120,
    proteinPer100g: 4.4,
    carbsPer100g: 21.3,
    fatPer100g: 1.9,
    fiberPer100g: 2.8,
    defaultServingSizeG: 185,
    defaultServingUnit: "g",
    isVerified: true,
  },

  // ─── LEGUMES & PULSES ────────────────────────────────────────
  {
    name: "Toor Dal (Cooked)",
    category: "LEGUMES_PULSES",
    caloriesPer100g: 116,
    proteinPer100g: 6.8,
    carbsPer100g: 19.6,
    fatPer100g: 0.4,
    fiberPer100g: 3.1,
    defaultServingSizeG: 200,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Moong Dal (Cooked)",
    category: "LEGUMES_PULSES",
    caloriesPer100g: 105,
    proteinPer100g: 7.0,
    carbsPer100g: 18.8,
    fatPer100g: 0.4,
    fiberPer100g: 2.7,
    defaultServingSizeG: 200,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Chana Dal (Cooked)",
    category: "LEGUMES_PULSES",
    caloriesPer100g: 164,
    proteinPer100g: 8.7,
    carbsPer100g: 27.6,
    fatPer100g: 2.7,
    fiberPer100g: 8.0,
    defaultServingSizeG: 200,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Rajma / Kidney Beans (Cooked)",
    category: "LEGUMES_PULSES",
    caloriesPer100g: 127,
    proteinPer100g: 8.7,
    carbsPer100g: 22.8,
    fatPer100g: 0.5,
    fiberPer100g: 7.4,
    defaultServingSizeG: 200,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Chickpeas / Chhole (Cooked)",
    category: "LEGUMES_PULSES",
    caloriesPer100g: 164,
    proteinPer100g: 8.9,
    carbsPer100g: 27.4,
    fatPer100g: 2.6,
    fiberPer100g: 7.6,
    defaultServingSizeG: 200,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Sambar (1 cup ~200ml)",
    category: "LEGUMES_PULSES",
    caloriesPer100g: 45,
    proteinPer100g: 2.5,
    carbsPer100g: 7.2,
    fatPer100g: 0.8,
    fiberPer100g: 1.5,
    defaultServingSizeG: 200,
    defaultServingUnit: "ml",
    isVerified: true,
  },

  // ─── DAIRY ───────────────────────────────────────────────────
  {
    name: "Whole Milk",
    category: "DAIRY",
    caloriesPer100g: 61,
    proteinPer100g: 3.2,
    carbsPer100g: 4.8,
    fatPer100g: 3.3,
    fiberPer100g: 0,
    defaultServingSizeG: 200,
    defaultServingUnit: "ml",
    isVerified: true,
  },
  {
    name: "Toned Milk (2% fat)",
    category: "DAIRY",
    caloriesPer100g: 44,
    proteinPer100g: 3.2,
    carbsPer100g: 4.8,
    fatPer100g: 1.5,
    fiberPer100g: 0,
    defaultServingSizeG: 200,
    defaultServingUnit: "ml",
    isVerified: true,
  },
  {
    name: "Paneer",
    category: "DAIRY",
    caloriesPer100g: 265,
    proteinPer100g: 18.3,
    carbsPer100g: 2.6,
    fatPer100g: 20.8,
    fiberPer100g: 0,
    defaultServingSizeG: 100,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Curd / Dahi (Plain)",
    category: "DAIRY",
    caloriesPer100g: 61,
    proteinPer100g: 3.1,
    carbsPer100g: 4.7,
    fatPer100g: 3.2,
    fiberPer100g: 0,
    defaultServingSizeG: 200,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Greek Yogurt (Plain, Full Fat)",
    category: "DAIRY",
    caloriesPer100g: 97,
    proteinPer100g: 9.0,
    carbsPer100g: 3.6,
    fatPer100g: 5.0,
    fiberPer100g: 0,
    defaultServingSizeG: 150,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Cottage Cheese / Paneer (Low Fat)",
    category: "DAIRY",
    caloriesPer100g: 98,
    proteinPer100g: 11.1,
    carbsPer100g: 3.4,
    fatPer100g: 4.3,
    fiberPer100g: 0,
    defaultServingSizeG: 100,
    defaultServingUnit: "g",
    isVerified: true,
  },

  // ─── EGGS ────────────────────────────────────────────────────
  {
    name: "Whole Egg",
    category: "EGGS",
    caloriesPer100g: 155,
    proteinPer100g: 12.6,
    carbsPer100g: 1.1,
    fatPer100g: 11.0,
    fiberPer100g: 0,
    defaultServingSizeG: 55,
    defaultServingUnit: "piece",
    isVerified: true,
  },
  {
    name: "Egg White",
    category: "EGGS",
    caloriesPer100g: 52,
    proteinPer100g: 10.9,
    carbsPer100g: 0.7,
    fatPer100g: 0.2,
    fiberPer100g: 0,
    defaultServingSizeG: 33,
    defaultServingUnit: "piece",
    isVerified: true,
  },
  {
    name: "Egg Yolk",
    category: "EGGS",
    caloriesPer100g: 322,
    proteinPer100g: 15.9,
    carbsPer100g: 3.6,
    fatPer100g: 26.5,
    fiberPer100g: 0,
    defaultServingSizeG: 17,
    defaultServingUnit: "piece",
    isVerified: true,
  },

  // ─── MEAT & POULTRY ──────────────────────────────────────────
  {
    name: "Chicken Breast (Cooked)",
    category: "MEAT_POULTRY",
    caloriesPer100g: 165,
    proteinPer100g: 31.0,
    carbsPer100g: 0,
    fatPer100g: 3.6,
    fiberPer100g: 0,
    defaultServingSizeG: 150,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Chicken Thigh (Cooked, Skinless)",
    category: "MEAT_POULTRY",
    caloriesPer100g: 209,
    proteinPer100g: 25.9,
    carbsPer100g: 0,
    fatPer100g: 10.9,
    fiberPer100g: 0,
    defaultServingSizeG: 100,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Lean Ground Beef (Cooked)",
    category: "MEAT_POULTRY",
    caloriesPer100g: 215,
    proteinPer100g: 26.1,
    carbsPer100g: 0,
    fatPer100g: 11.8,
    fiberPer100g: 0,
    defaultServingSizeG: 100,
    defaultServingUnit: "g",
    isVerified: true,
  },

  // ─── SEAFOOD ─────────────────────────────────────────────────
  {
    name: "Rohu Fish (Cooked)",
    category: "SEAFOOD",
    caloriesPer100g: 97,
    proteinPer100g: 16.6,
    carbsPer100g: 0,
    fatPer100g: 3.4,
    fiberPer100g: 0,
    defaultServingSizeG: 150,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Tuna (Canned in Water)",
    category: "SEAFOOD",
    caloriesPer100g: 116,
    proteinPer100g: 25.5,
    carbsPer100g: 0,
    fatPer100g: 1.0,
    fiberPer100g: 0,
    defaultServingSizeG: 100,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Salmon (Cooked)",
    category: "SEAFOOD",
    caloriesPer100g: 206,
    proteinPer100g: 28.8,
    carbsPer100g: 0,
    fatPer100g: 9.8,
    fiberPer100g: 0,
    defaultServingSizeG: 150,
    defaultServingUnit: "g",
    isVerified: true,
  },

  // ─── VEGETABLES ──────────────────────────────────────────────
  {
    name: "Spinach (Raw)",
    category: "VEGETABLES",
    caloriesPer100g: 23,
    proteinPer100g: 2.9,
    carbsPer100g: 3.6,
    fatPer100g: 0.4,
    fiberPer100g: 2.2,
    defaultServingSizeG: 100,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Broccoli (Cooked)",
    category: "VEGETABLES",
    caloriesPer100g: 35,
    proteinPer100g: 2.4,
    carbsPer100g: 7.2,
    fatPer100g: 0.4,
    fiberPer100g: 3.3,
    defaultServingSizeG: 150,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Sweet Potato (Baked)",
    category: "VEGETABLES",
    caloriesPer100g: 90,
    proteinPer100g: 2.0,
    carbsPer100g: 20.7,
    fatPer100g: 0.1,
    fiberPer100g: 3.3,
    defaultServingSizeG: 150,
    defaultServingUnit: "g",
    isVerified: true,
  },

  // ─── FRUITS ──────────────────────────────────────────────────
  {
    name: "Banana",
    category: "FRUITS",
    caloriesPer100g: 89,
    proteinPer100g: 1.1,
    carbsPer100g: 23.0,
    fatPer100g: 0.3,
    fiberPer100g: 2.6,
    defaultServingSizeG: 120,
    defaultServingUnit: "piece",
    isVerified: true,
  },
  {
    name: "Apple",
    category: "FRUITS",
    caloriesPer100g: 52,
    proteinPer100g: 0.3,
    carbsPer100g: 14.0,
    fatPer100g: 0.2,
    fiberPer100g: 2.4,
    defaultServingSizeG: 180,
    defaultServingUnit: "piece",
    isVerified: true,
  },
  {
    name: "Mango",
    category: "FRUITS",
    caloriesPer100g: 60,
    proteinPer100g: 0.8,
    carbsPer100g: 15.0,
    fatPer100g: 0.4,
    fiberPer100g: 1.6,
    defaultServingSizeG: 200,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Papaya",
    category: "FRUITS",
    caloriesPer100g: 43,
    proteinPer100g: 0.5,
    carbsPer100g: 10.8,
    fatPer100g: 0.3,
    fiberPer100g: 1.7,
    defaultServingSizeG: 200,
    defaultServingUnit: "g",
    isVerified: true,
  },

  // ─── NUTS & SEEDS ────────────────────────────────────────────
  {
    name: "Peanut Butter",
    category: "NUTS_SEEDS",
    caloriesPer100g: 588,
    proteinPer100g: 25.1,
    carbsPer100g: 20.1,
    fatPer100g: 50.4,
    fiberPer100g: 5.9,
    defaultServingSizeG: 32,
    defaultServingUnit: "tbsp",
    isVerified: true,
  },
  {
    name: "Almonds",
    category: "NUTS_SEEDS",
    caloriesPer100g: 579,
    proteinPer100g: 21.2,
    carbsPer100g: 21.7,
    fatPer100g: 49.9,
    fiberPer100g: 12.5,
    defaultServingSizeG: 28,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Cashews",
    category: "NUTS_SEEDS",
    caloriesPer100g: 553,
    proteinPer100g: 18.2,
    carbsPer100g: 30.2,
    fatPer100g: 43.9,
    fiberPer100g: 3.3,
    defaultServingSizeG: 28,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Walnuts",
    category: "NUTS_SEEDS",
    caloriesPer100g: 654,
    proteinPer100g: 15.2,
    carbsPer100g: 13.7,
    fatPer100g: 65.2,
    fiberPer100g: 6.7,
    defaultServingSizeG: 28,
    defaultServingUnit: "g",
    isVerified: true,
  },
  {
    name: "Chia Seeds",
    category: "NUTS_SEEDS",
    caloriesPer100g: 486,
    proteinPer100g: 16.5,
    carbsPer100g: 42.1,
    fatPer100g: 30.7,
    fiberPer100g: 34.4,
    defaultServingSizeG: 20,
    defaultServingUnit: "g",
    isVerified: true,
  },

  // ─── SUPPLEMENTS ─────────────────────────────────────────────
  {
    name: "Whey Protein Powder",
    category: "SUPPLEMENTS",
    caloriesPer100g: 382,
    proteinPer100g: 74.0,
    carbsPer100g: 9.2,
    fatPer100g: 6.9,
    fiberPer100g: 0,
    defaultServingSizeG: 30,
    defaultServingUnit: "scoop",
    isVerified: true,
  },
  {
    name: "Casein Protein Powder",
    category: "SUPPLEMENTS",
    caloriesPer100g: 380,
    proteinPer100g: 75.0,
    carbsPer100g: 10.0,
    fatPer100g: 5.0,
    fiberPer100g: 0,
    defaultServingSizeG: 33,
    defaultServingUnit: "scoop",
    isVerified: true,
  },
  {
    name: "Creatine Monohydrate",
    category: "SUPPLEMENTS",
    caloriesPer100g: 0,
    proteinPer100g: 0,
    carbsPer100g: 0,
    fatPer100g: 0,
    fiberPer100g: 0,
    defaultServingSizeG: 5,
    defaultServingUnit: "g",
    isVerified: true,
  },

  // ─── FATS & OILS ─────────────────────────────────────────────
  {
    name: "Ghee (Clarified Butter)",
    category: "FATS_OILS",
    caloriesPer100g: 900,
    proteinPer100g: 0,
    carbsPer100g: 0,
    fatPer100g: 100,
    fiberPer100g: 0,
    defaultServingSizeG: 10,
    defaultServingUnit: "tsp",
    isVerified: true,
  },
  {
    name: "Olive Oil",
    category: "FATS_OILS",
    caloriesPer100g: 884,
    proteinPer100g: 0,
    carbsPer100g: 0,
    fatPer100g: 100,
    fiberPer100g: 0,
    defaultServingSizeG: 13.5,
    defaultServingUnit: "tbsp",
    isVerified: true,
  },
  {
    name: "Coconut Oil",
    category: "FATS_OILS",
    caloriesPer100g: 862,
    proteinPer100g: 0,
    carbsPer100g: 0,
    fatPer100g: 100,
    fiberPer100g: 0,
    defaultServingSizeG: 13.5,
    defaultServingUnit: "tbsp",
    isVerified: true,
  },
];

import { indianFoods } from "./indian-foods";
const allFoods = [...foods, ...indianFoods];

// ─────────────────────────────────────────────
// Exercise Library Seed
// ─────────────────────────────────────────────

const exercises = [
  // KEY LIFTS — Strength
  {
    name: "Barbell Back Squat",
    description: "The foundational lower body strength exercise.",
    primaryMuscles: ["QUADS", "GLUTES"],
    secondaryMuscles: ["HAMSTRINGS", "CORE", "TRAPS"],
    category: "STRENGTH",
    equipment: "BARBELL",
    isCompoundLift: true,
    isKeyLift: true,
  },
  {
    name: "Barbell Bench Press",
    description: "Primary horizontal pushing strength exercise.",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["FRONT_DELTS", "TRICEPS"],
    category: "STRENGTH",
    equipment: "BARBELL",
    isCompoundLift: true,
    isKeyLift: true,
  },
  {
    name: "Conventional Deadlift",
    description: "Full-body posterior chain strength movement.",
    primaryMuscles: ["HAMSTRINGS", "GLUTES", "BACK"],
    secondaryMuscles: ["TRAPS", "CORE", "QUADS", "FOREARMS"],
    category: "STRENGTH",
    equipment: "BARBELL",
    isCompoundLift: true,
    isKeyLift: true,
  },
  {
    name: "Overhead Press (OHP)",
    description: "Vertical push — primary shoulder strength builder.",
    primaryMuscles: ["SHOULDERS", "FRONT_DELTS"],
    secondaryMuscles: ["TRICEPS", "TRAPS", "CORE"],
    category: "STRENGTH",
    equipment: "BARBELL",
    isCompoundLift: true,
    isKeyLift: true,
  },
  {
    name: "Pull-up / Chin-up",
    description: "Vertical pull — key lat and bicep builder.",
    primaryMuscles: ["LATS"],
    secondaryMuscles: ["BICEPS", "REAR_DELTS", "CORE"],
    category: "STRENGTH",
    equipment: "BODYWEIGHT",
    isCompoundLift: true,
    isKeyLift: true,
  },
  {
    name: "Barbell Row",
    description: "Horizontal pull — builds a thick back.",
    primaryMuscles: ["BACK", "LATS"],
    secondaryMuscles: ["BICEPS", "REAR_DELTS", "TRAPS"],
    category: "STRENGTH",
    equipment: "BARBELL",
    isCompoundLift: true,
    isKeyLift: true,
  },
  {
    name: "Romanian Deadlift",
    description: "Hinge movement targeting hamstrings and glutes.",
    primaryMuscles: ["HAMSTRINGS", "GLUTES"],
    secondaryMuscles: ["BACK", "CORE"],
    category: "STRENGTH",
    equipment: "BARBELL",
    isCompoundLift: true,
    isKeyLift: false,
  },

  // HYPERTROPHY
  {
    name: "Incline Dumbbell Press",
    description: "Upper chest emphasis pressing movement.",
    primaryMuscles: ["UPPER_CHEST"],
    secondaryMuscles: ["FRONT_DELTS", "TRICEPS"],
    category: "HYPERTROPHY",
    equipment: "DUMBBELL",
    isCompoundLift: false,
    isKeyLift: false,
  },
  {
    name: "Dumbbell Lateral Raise",
    description: "Isolation for lateral deltoid width.",
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: [],
    category: "HYPERTROPHY",
    equipment: "DUMBBELL",
    isCompoundLift: false,
    isKeyLift: false,
  },
  {
    name: "Cable Fly",
    description: "Chest isolation with constant tension.",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["FRONT_DELTS"],
    category: "HYPERTROPHY",
    equipment: "CABLE",
    isCompoundLift: false,
    isKeyLift: false,
  },
  {
    name: "Lat Pulldown",
    description: "Vertical pull — lat width builder.",
    primaryMuscles: ["LATS"],
    secondaryMuscles: ["BICEPS", "REAR_DELTS"],
    category: "HYPERTROPHY",
    equipment: "CABLE",
    isCompoundLift: false,
    isKeyLift: false,
  },
  {
    name: "Seated Cable Row",
    description: "Horizontal pull for back thickness.",
    primaryMuscles: ["BACK"],
    secondaryMuscles: ["BICEPS", "REAR_DELTS"],
    category: "HYPERTROPHY",
    equipment: "CABLE",
    isCompoundLift: false,
    isKeyLift: false,
  },
  {
    name: "Dumbbell Curl",
    description: "Bicep isolation exercise.",
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: ["FOREARMS"],
    category: "HYPERTROPHY",
    equipment: "DUMBBELL",
    isCompoundLift: false,
    isKeyLift: false,
  },
  {
    name: "Tricep Rope Pushdown",
    description: "Tricep isolation using cable.",
    primaryMuscles: ["TRICEPS"],
    secondaryMuscles: [],
    category: "HYPERTROPHY",
    equipment: "CABLE",
    isCompoundLift: false,
    isKeyLift: false,
  },
  {
    name: "Leg Press",
    description: "Machine-based quad and glute builder.",
    primaryMuscles: ["QUADS", "GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    category: "HYPERTROPHY",
    equipment: "MACHINE",
    isCompoundLift: false,
    isKeyLift: false,
  },
  {
    name: "Leg Curl (Machine)",
    description: "Hamstring isolation exercise.",
    primaryMuscles: ["HAMSTRINGS"],
    secondaryMuscles: [],
    category: "HYPERTROPHY",
    equipment: "MACHINE",
    isCompoundLift: false,
    isKeyLift: false,
  },
  {
    name: "Hip Thrust",
    description: "Glute isolation and development.",
    primaryMuscles: ["GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    category: "HYPERTROPHY",
    equipment: "BARBELL",
    isCompoundLift: false,
    isKeyLift: false,
  },
  {
    name: "Plank",
    description: "Core stability exercise.",
    primaryMuscles: ["CORE"],
    secondaryMuscles: [],
    category: "STRENGTH",
    equipment: "BODYWEIGHT",
    isCompoundLift: false,
    isKeyLift: false,
  },

  // CARDIO / CONDITIONING
  {
    name: "Running",
    description: "Outdoor or treadmill running.",
    primaryMuscles: ["QUADS", "HAMSTRINGS", "CALVES"],
    secondaryMuscles: ["CORE", "GLUTES"],
    category: "CARDIO",
    equipment: "CARDIO_MACHINE",
    isCompoundLift: false,
    isKeyLift: false,
  },
  {
    name: "Cycling",
    description: "Stationary bike or outdoor cycling.",
    primaryMuscles: ["QUADS", "HAMSTRINGS"],
    secondaryMuscles: ["CALVES", "GLUTES"],
    category: "CARDIO",
    equipment: "CARDIO_MACHINE",
    isCompoundLift: false,
    isKeyLift: false,
  },
  {
    name: "Jump Rope",
    description: "High-intensity conditioning tool.",
    primaryMuscles: ["CALVES"],
    secondaryMuscles: ["CORE", "SHOULDERS"],
    category: "CONDITIONING",
    equipment: "OTHER",
    isCompoundLift: false,
    isKeyLift: false,
  },
];

async function main() {
  console.log("🌱 Starting FitStack database seed...");

  // ─── Seed Foods ───────────────────────────────────────────────
  console.log(`\n📦 Seeding ${allFoods.length} foods...`);

  await prisma.food.createMany({
    data: allFoods.map((food) => ({
      name: food.name,
      category: food.category as any,
      caloriesPer100g: food.caloriesPer100g,
      proteinPer100g: food.proteinPer100g,
      carbsPer100g: food.carbsPer100g,
      fatPer100g: food.fatPer100g,
      fiberPer100g: food.fiberPer100g ?? null,
      defaultServingSizeG: food.defaultServingSizeG,
      defaultServingUnit: food.defaultServingUnit as any,
      isVerified: true,
      isPublic: true,
    })),
    skipDuplicates: false,
  });
  const foodCount = allFoods.length;
  console.log(`✅ Seeded ${foodCount} foods`);

  // ─── Seed Exercises ───────────────────────────────────────────
  console.log(`\n💪 Seeding ${exercises.length} exercises...`);
  let exerciseCount = 0;

  for (const exercise of exercises) {
    await prisma.exercise.upsert({
      where: { name: exercise.name },
      create: {
        ...exercise,
        primaryMuscles: exercise.primaryMuscles as any,
        secondaryMuscles: exercise.secondaryMuscles as any,
        category: exercise.category as any,
        equipment: exercise.equipment as any,
        isPublic: true,
      },
      update: {
        description: exercise.description,
        primaryMuscles: exercise.primaryMuscles as any,
        secondaryMuscles: exercise.secondaryMuscles as any,
        category: exercise.category as any,
        equipment: exercise.equipment as any,
        isCompoundLift: exercise.isCompoundLift,
        isKeyLift: exercise.isKeyLift,
      },
    });
    exerciseCount++;
  }
  console.log(`✅ Seeded ${exerciseCount} exercises`);

  console.log("\n🎉 Seed complete!");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
